import Head from 'next/head'
import Image from 'next/image'
import styled from "@emotion/styled"

const Container = styled.div`
  padding: 0 2rem;  
`;
const Main = styled.main`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
const BlogTitle = styled.h1`
  color: #0070f3;
  text-decoration: none;
`;

const title: string = "PAV Blog" 

export default function Home() {
  return (
    <Container>
      <Head>
        <title>PAV blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <BlogTitle>PAV blog</BlogTitle>
      </Main>

      
    </Container>
  )
}
